services:
  web:
    image: nginx:alpine
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
    ports:
      - "8003:80"
    restart: unless-stopped
  editor:
    build: .
    volumes:
      - ./www-edit:/var/www/html
      - ./www/data:/var/www/data
    ports: 
      - "8004:80"
    restart: unless-stopped